class UserException(Exception):
    """Raised when User was not found in current data source"""
